namespace JapLearn.Models;

public class JapaneseWord
{
    public string Word { get; set; } = "";
    public string Romaji { get; set; } = "";
    public string Meaning { get; set; } = "";
    public string Type { get; set; } = "";

    public static List<JapaneseWord> All = new()
    {
        // ===================== SỐ ĐẾM =====================
        new() { Word = "ぜろ", Romaji = "zero", Meaning = "số 0", Type = "Số đếm" },
        new() { Word = "いち", Romaji = "ichi", Meaning = "số 1", Type = "Số đếm" },
        new() { Word = "に", Romaji = "ni", Meaning = "số 2", Type = "Số đếm" },
        new() { Word = "さん", Romaji = "san", Meaning = "số 3", Type = "Số đếm" },
        new() { Word = "し/よん", Romaji = "shi/yon", Meaning = "số 4", Type = "Số đếm" },
        new() { Word = "ご", Romaji = "go", Meaning = "số 5", Type = "Số đếm" },
        new() { Word = "ろく", Romaji = "roku", Meaning = "số 6", Type = "Số đếm" },
        new() { Word = "しち/なな", Romaji = "shichi/nana", Meaning = "số 7", Type = "Số đếm" },
        new() { Word = "はち", Romaji = "hachi", Meaning = "số 8", Type = "Số đếm" },
        new() { Word = "きゅう/く", Romaji = "kyuu/ku", Meaning = "số 9", Type = "Số đếm" },
        new() { Word = "じゅう", Romaji = "juu", Meaning = "số 10", Type = "Số đếm" },
        new() { Word = "ひゃく", Romaji = "hyaku", Meaning = "số 100", Type = "Số đếm" },
        new() { Word = "せん", Romaji = "sen", Meaning = "số 1000", Type = "Số đếm" },
        new() { Word = "まん", Romaji = "man", Meaning = "số 10000", Type = "Số đếm" },
        new() { Word = "ひとつ", Romaji = "hitotsu", Meaning = "1 cái", Type = "Số đếm" },
        new() { Word = "ふたつ", Romaji = "futatsu", Meaning = "2 cái", Type = "Số đếm" },
        new() { Word = "みっつ", Romaji = "mittsu", Meaning = "3 cái", Type = "Số đếm" },
        new() { Word = "よっつ", Romaji = "yottsu", Meaning = "4 cái", Type = "Số đếm" },
        new() { Word = "いつつ", Romaji = "itsutsu", Meaning = "5 cái", Type = "Số đếm" },
        new() { Word = "むっつ", Romaji = "muttsu", Meaning = "6 cái", Type = "Số đếm" },
        new() { Word = "ななつ", Romaji = "nanatsu", Meaning = "7 cái", Type = "Số đếm" },
        new() { Word = "やっつ", Romaji = "yattsu", Meaning = "8 cái", Type = "Số đếm" },
        new() { Word = "ここのつ", Romaji = "kokonotsu", Meaning = "9 cái", Type = "Số đếm" },
        new() { Word = "とう", Romaji = "tou", Meaning = "10 cái", Type = "Số đếm" },
        new() { Word = "いくつ", Romaji = "ikutsu", Meaning = "bao nhiêu cái", Type = "Số đếm" },
        new() { Word = "ひとり", Romaji = "hitori", Meaning = "1 người", Type = "Số đếm" },
        new() { Word = "ふたり", Romaji = "futari", Meaning = "2 người", Type = "Số đếm" },
        new() { Word = "なんにん", Romaji = "nannin", Meaning = "mấy người", Type = "Số đếm" },

        // ===================== NGÀY THÁNG =====================
        new() { Word = "にちようび", Romaji = "nichiyoubi", Meaning = "Chủ nhật", Type = "Ngày tháng" },
        new() { Word = "げつようび", Romaji = "getsuyoubi", Meaning = "Thứ hai", Type = "Ngày tháng" },
        new() { Word = "かようび", Romaji = "kayoubi", Meaning = "Thứ ba", Type = "Ngày tháng" },
        new() { Word = "すいようび", Romaji = "suiyoubi", Meaning = "Thứ tư", Type = "Ngày tháng" },
        new() { Word = "もくようび", Romaji = "mokuyoubi", Meaning = "Thứ năm", Type = "Ngày tháng" },
        new() { Word = "きんようび", Romaji = "kinyoubi", Meaning = "Thứ sáu", Type = "Ngày tháng" },
        new() { Word = "どようび", Romaji = "doyoubi", Meaning = "Thứ bảy", Type = "Ngày tháng" },
        new() { Word = "なんようび", Romaji = "nanyoubi", Meaning = "thứ mấy", Type = "Ngày tháng" },
        new() { Word = "きょう", Romaji = "kyou", Meaning = "hôm nay", Type = "Ngày tháng" },
        new() { Word = "あした", Romaji = "ashita", Meaning = "ngày mai", Type = "Ngày tháng" },
        new() { Word = "きのう", Romaji = "kinou", Meaning = "hôm qua", Type = "Ngày tháng" },
        new() { Word = "あさって", Romaji = "asatte", Meaning = "ngày kia", Type = "Ngày tháng" },
        new() { Word = "おととい", Romaji = "ototoi", Meaning = "hôm kia", Type = "Ngày tháng" },
        new() { Word = "まいにち", Romaji = "mainichi", Meaning = "mỗi ngày", Type = "Ngày tháng" },
        new() { Word = "まいしゅう", Romaji = "maishuu", Meaning = "mỗi tuần", Type = "Ngày tháng" },
        new() { Word = "まいげつ", Romaji = "maigetsu", Meaning = "mỗi tháng", Type = "Ngày tháng" },
        new() { Word = "まいとし", Romaji = "maitoshi", Meaning = "mỗi năm", Type = "Ngày tháng" },
        new() { Word = "こんしゅう", Romaji = "konshuu", Meaning = "tuần này", Type = "Ngày tháng" },
        new() { Word = "らいしゅう", Romaji = "raishuu", Meaning = "tuần sau", Type = "Ngày tháng" },
        new() { Word = "せんしゅう", Romaji = "senshuu", Meaning = "tuần trước", Type = "Ngày tháng" },
        new() { Word = "こんげつ", Romaji = "kongetsu", Meaning = "tháng này", Type = "Ngày tháng" },
        new() { Word = "らいげつ", Romaji = "raigetsu", Meaning = "tháng sau", Type = "Ngày tháng" },
        new() { Word = "せんげつ", Romaji = "sengetsu", Meaning = "tháng trước", Type = "Ngày tháng" },
        new() { Word = "ことし", Romaji = "kotoshi", Meaning = "năm nay", Type = "Ngày tháng" },
        new() { Word = "らいねん", Romaji = "rainen", Meaning = "năm sau", Type = "Ngày tháng" },
        new() { Word = "きょねん", Romaji = "kyonen", Meaning = "năm ngoái", Type = "Ngày tháng" },
        new() { Word = "いま", Romaji = "ima", Meaning = "bây giờ", Type = "Ngày tháng" },
        new() { Word = "じかん", Romaji = "jikan", Meaning = "thời gian", Type = "Ngày tháng" },
        new() { Word = "ごぜん", Romaji = "gozen", Meaning = "sáng (AM)", Type = "Ngày tháng" },
        new() { Word = "ごご", Romaji = "gogo", Meaning = "chiều (PM)", Type = "Ngày tháng" },
        new() { Word = "いちがつ", Romaji = "ichigatsu", Meaning = "tháng 1", Type = "Ngày tháng" },
        new() { Word = "にがつ", Romaji = "nigatsu", Meaning = "tháng 2", Type = "Ngày tháng" },
        new() { Word = "さんがつ", Romaji = "sangatsu", Meaning = "tháng 3", Type = "Ngày tháng" },
        new() { Word = "しがつ", Romaji = "shigatsu", Meaning = "tháng 4", Type = "Ngày tháng" },
        new() { Word = "ごがつ", Romaji = "gogatsu", Meaning = "tháng 5", Type = "Ngày tháng" },
        new() { Word = "ろくがつ", Romaji = "rokugatsu", Meaning = "tháng 6", Type = "Ngày tháng" },
        new() { Word = "しちがつ", Romaji = "shichigatsu", Meaning = "tháng 7", Type = "Ngày tháng" },
        new() { Word = "はちがつ", Romaji = "hachigatsu", Meaning = "tháng 8", Type = "Ngày tháng" },
        new() { Word = "くがつ", Romaji = "kugatsu", Meaning = "tháng 9", Type = "Ngày tháng" },
        new() { Word = "じゅうがつ", Romaji = "juugatsu", Meaning = "tháng 10", Type = "Ngày tháng" },
        new() { Word = "じゅういちがつ", Romaji = "juuichigatsu", Meaning = "tháng 11", Type = "Ngày tháng" },
        new() { Word = "じゅうにがつ", Romaji = "juunigatsu", Meaning = "tháng 12", Type = "Ngày tháng" },
        new() { Word = "ついたち", Romaji = "tsuitachi", Meaning = "ngày 1", Type = "Ngày tháng" },
        new() { Word = "ふつか", Romaji = "futsuka", Meaning = "ngày 2", Type = "Ngày tháng" },
        new() { Word = "みっか", Romaji = "mikka", Meaning = "ngày 3", Type = "Ngày tháng" },
        new() { Word = "よっか", Romaji = "yokka", Meaning = "ngày 4", Type = "Ngày tháng" },
        new() { Word = "いつか", Romaji = "itsuka", Meaning = "ngày 5", Type = "Ngày tháng" },
        new() { Word = "むいか", Romaji = "muika", Meaning = "ngày 6", Type = "Ngày tháng" },
        new() { Word = "なのか", Romaji = "nanoka", Meaning = "ngày 7", Type = "Ngày tháng" },
        new() { Word = "ようか", Romaji = "youka", Meaning = "ngày 8", Type = "Ngày tháng" },
        new() { Word = "ここのか", Romaji = "kokonoka", Meaning = "ngày 9", Type = "Ngày tháng" },
        new() { Word = "とおか", Romaji = "tooka", Meaning = "ngày 10", Type = "Ngày tháng" },
        new() { Word = "はつか", Romaji = "hatsuka", Meaning = "ngày 20", Type = "Ngày tháng" },
        new() { Word = "なんにち", Romaji = "nannichi", Meaning = "ngày mấy", Type = "Ngày tháng" },
        new() { Word = "こんばん", Romaji = "konban", Meaning = "tối nay", Type = "Ngày tháng" },
        new() { Word = "けさ", Romaji = "kesa", Meaning = "sáng nay", Type = "Ngày tháng" },

        // ===================== GIA ĐÌNH =====================
        new() { Word = "かぞく", Romaji = "kazoku", Meaning = "gia đình", Type = "Gia đình" },
        new() { Word = "おとうさん", Romaji = "otousan", Meaning = "bố", Type = "Gia đình" },
        new() { Word = "おかあさん", Romaji = "okaasan", Meaning = "mẹ", Type = "Gia đình" },
        new() { Word = "おにいさん", Romaji = "oniisan", Meaning = "anh trai", Type = "Gia đình" },
        new() { Word = "おねえさん", Romaji = "oneesan", Meaning = "chị gái", Type = "Gia đình" },
        new() { Word = "おとうと", Romaji = "otouto", Meaning = "em trai", Type = "Gia đình" },
        new() { Word = "いもうと", Romaji = "imouto", Meaning = "em gái", Type = "Gia đình" },
        new() { Word = "おじいさん", Romaji = "ojiisan", Meaning = "ông", Type = "Gia đình" },
        new() { Word = "おばあさん", Romaji = "obaasan", Meaning = "bà", Type = "Gia đình" },
        new() { Word = "おじさん", Romaji = "ojisan", Meaning = "chú/bác", Type = "Gia đình" },
        new() { Word = "おばさん", Romaji = "obasan", Meaning = "cô/dì", Type = "Gia đình" },
        new() { Word = "りょうしん", Romaji = "ryoushin", Meaning = "bố mẹ", Type = "Gia đình" },
        new() { Word = "こども", Romaji = "kodomo", Meaning = "trẻ em", Type = "Gia đình" },
        new() { Word = "あかちゃん", Romaji = "akachan", Meaning = "em bé", Type = "Gia đình" },
        new() { Word = "むすこ", Romaji = "musuko", Meaning = "con trai", Type = "Gia đình" },
        new() { Word = "むすめ", Romaji = "musume", Meaning = "con gái", Type = "Gia đình" },
        new() { Word = "きょうだい", Romaji = "kyoudai", Meaning = "anh chị em", Type = "Gia đình" },
        new() { Word = "ふうふ", Romaji = "fuufu", Meaning = "vợ chồng", Type = "Gia đình" },
        new() { Word = "おっと", Romaji = "otto", Meaning = "chồng", Type = "Gia đình" },
        new() { Word = "つま", Romaji = "tsuma", Meaning = "vợ", Type = "Gia đình" },
        new() { Word = "しんせき", Romaji = "shinseki", Meaning = "họ hàng", Type = "Gia đình" },

        // ===================== MÀU SẮC =====================
        new() { Word = "あか", Romaji = "aka", Meaning = "màu đỏ", Type = "Danh từ" },
        new() { Word = "あお", Romaji = "ao", Meaning = "màu xanh lam", Type = "Danh từ" },
        new() { Word = "きいろ", Romaji = "kiiro", Meaning = "màu vàng", Type = "Danh từ" },
        new() { Word = "しろ", Romaji = "shiro", Meaning = "màu trắng", Type = "Danh từ" },
        new() { Word = "くろ", Romaji = "kuro", Meaning = "màu đen", Type = "Danh từ" },
        new() { Word = "みどり", Romaji = "midori", Meaning = "màu xanh lá", Type = "Danh từ" },
        new() { Word = "むらさき", Romaji = "murasaki", Meaning = "màu tím", Type = "Danh từ" },
        new() { Word = "ちゃいろ", Romaji = "chairo", Meaning = "màu nâu", Type = "Danh từ" },
        new() { Word = "はいいろ", Romaji = "haiiro", Meaning = "màu xám", Type = "Danh từ" },
        new() { Word = "ピンク", Romaji = "pinku", Meaning = "màu hồng", Type = "Danh từ" },
        new() { Word = "オレンジ", Romaji = "orenji", Meaning = "màu cam", Type = "Danh từ" },

        // ===================== ĐỒ VẬT =====================
        new() { Word = "つくえ", Romaji = "tsukue", Meaning = "cái bàn", Type = "Đồ vật" },
        new() { Word = "いす", Romaji = "isu", Meaning = "cái ghế", Type = "Đồ vật" },
        new() { Word = "ほん", Romaji = "hon", Meaning = "quyển sách", Type = "Đồ vật" },
        new() { Word = "かばん", Romaji = "kaban", Meaning = "cặp sách", Type = "Đồ vật" },
        new() { Word = "とけい", Romaji = "tokei", Meaning = "đồng hồ", Type = "Đồ vật" },
        new() { Word = "でんわ", Romaji = "denwa", Meaning = "điện thoại", Type = "Đồ vật" },
        new() { Word = "テレビ", Romaji = "terebi", Meaning = "tivi", Type = "Đồ vật" },
        new() { Word = "ラジオ", Romaji = "rajio", Meaning = "radio", Type = "Đồ vật" },
        new() { Word = "コンピューター", Romaji = "konpyuutaa", Meaning = "máy tính", Type = "Đồ vật" },
        new() { Word = "まど", Romaji = "mado", Meaning = "cửa sổ", Type = "Đồ vật" },
        new() { Word = "ドア", Romaji = "doa", Meaning = "cửa ra vào", Type = "Đồ vật" },
        new() { Word = "かぎ", Romaji = "kagi", Meaning = "chìa khóa", Type = "Đồ vật" },
        new() { Word = "かさ", Romaji = "kasa", Meaning = "cái ô", Type = "Đồ vật" },
        new() { Word = "かがみ", Romaji = "kagami", Meaning = "cái gương", Type = "Đồ vật" },
        new() { Word = "かみ", Romaji = "kami", Meaning = "giấy", Type = "Đồ vật" },
        new() { Word = "はさみ", Romaji = "hasami", Meaning = "cái kéo", Type = "Đồ vật" },
        new() { Word = "ナイフ", Romaji = "naifu", Meaning = "con dao", Type = "Đồ vật" },
        new() { Word = "フォーク", Romaji = "fooku", Meaning = "cái dĩa", Type = "Đồ vật" },
        new() { Word = "スプーン", Romaji = "supuun", Meaning = "cái thìa", Type = "Đồ vật" },
        new() { Word = "コップ", Romaji = "koppu", Meaning = "cái cốc", Type = "Đồ vật" },
        new() { Word = "はし", Romaji = "hashi", Meaning = "đôi đũa", Type = "Đồ vật" },
        new() { Word = "おさら", Romaji = "osara", Meaning = "cái đĩa", Type = "Đồ vật" },
        new() { Word = "はこ", Romaji = "hako", Meaning = "cái hộp", Type = "Đồ vật" },
        new() { Word = "ゴミばこ", Romaji = "gomibako", Meaning = "thùng rác", Type = "Đồ vật" },
        new() { Word = "でんき", Romaji = "denki", Meaning = "đèn điện", Type = "Đồ vật" },
        new() { Word = "エアコン", Romaji = "eakon", Meaning = "máy lạnh", Type = "Đồ vật" },
        new() { Word = "カーテン", Romaji = "kaaten", Meaning = "rèm cửa", Type = "Đồ vật" },
        new() { Word = "たんす", Romaji = "tansu", Meaning = "tủ quần áo", Type = "Đồ vật" },
        new() { Word = "ベッド", Romaji = "beddo", Meaning = "giường", Type = "Đồ vật" },
        new() { Word = "ふとん", Romaji = "futon", Meaning = "chăn/gối", Type = "Đồ vật" },
        new() { Word = "まくら", Romaji = "makura", Meaning = "cái gối", Type = "Đồ vật" },
        new() { Word = "たおる", Romaji = "taoru", Meaning = "cái khăn", Type = "Đồ vật" },
        new() { Word = "せっけん", Romaji = "sekken", Meaning = "xà phòng", Type = "Đồ vật" },
        new() { Word = "くし", Romaji = "kushi", Meaning = "cái lược", Type = "Đồ vật" },
        new() { Word = "かめら", Romaji = "kamera", Meaning = "máy ảnh", Type = "Đồ vật" },
        new() { Word = "ざっし", Romaji = "zasshi", Meaning = "tạp chí", Type = "Đồ vật" },
        new() { Word = "にっき", Romaji = "nikki", Meaning = "nhật ký", Type = "Đồ vật" },
        new() { Word = "てがみ", Romaji = "tegami", Meaning = "lá thư", Type = "Đồ vật" },
        new() { Word = "きって", Romaji = "kitte", Meaning = "con tem", Type = "Đồ vật" },
        new() { Word = "さいふ", Romaji = "saifu", Meaning = "cái ví", Type = "Đồ vật" },

        // ===================== THỨC ĂN =====================
        new() { Word = "ごはん", Romaji = "gohan", Meaning = "cơm", Type = "Thức ăn" },
        new() { Word = "パン", Romaji = "pan", Meaning = "bánh mì", Type = "Thức ăn" },
        new() { Word = "ぎゅうにゅう", Romaji = "gyuunyuu", Meaning = "sữa bò", Type = "Thức ăn" },
        new() { Word = "みず", Romaji = "mizu", Meaning = "nước", Type = "Thức ăn" },
        new() { Word = "おちゃ", Romaji = "ocha", Meaning = "trà xanh", Type = "Thức ăn" },
        new() { Word = "コーヒー", Romaji = "koohii", Meaning = "cà phê", Type = "Thức ăn" },
        new() { Word = "ジュース", Romaji = "juusu", Meaning = "nước ép", Type = "Thức ăn" },
        new() { Word = "ビール", Romaji = "biiru", Meaning = "bia", Type = "Thức ăn" },
        new() { Word = "ワイン", Romaji = "wain", Meaning = "rượu vang", Type = "Thức ăn" },
        new() { Word = "さかな", Romaji = "sakana", Meaning = "cá", Type = "Thức ăn" },
        new() { Word = "にく", Romaji = "niku", Meaning = "thịt", Type = "Thức ăn" },
        new() { Word = "とりにく", Romaji = "toriniku", Meaning = "thịt gà", Type = "Thức ăn" },
        new() { Word = "ぶたにく", Romaji = "butaniku", Meaning = "thịt heo", Type = "Thức ăn" },
        new() { Word = "ぎゅうにく", Romaji = "gyuuniku", Meaning = "thịt bò", Type = "Thức ăn" },
        new() { Word = "たまご", Romaji = "tamago", Meaning = "trứng", Type = "Thức ăn" },
        new() { Word = "やさい", Romaji = "yasai", Meaning = "rau củ", Type = "Thức ăn" },
        new() { Word = "くだもの", Romaji = "kudamono", Meaning = "trái cây", Type = "Thức ăn" },
        new() { Word = "りんご", Romaji = "ringo", Meaning = "táo", Type = "Thức ăn" },
        new() { Word = "みかん", Romaji = "mikan", Meaning = "quýt", Type = "Thức ăn" },
        new() { Word = "バナナ", Romaji = "banana", Meaning = "chuối", Type = "Thức ăn" },
        new() { Word = "いちご", Romaji = "ichigo", Meaning = "dâu tây", Type = "Thức ăn" },
        new() { Word = "ぶどう", Romaji = "budou", Meaning = "nho", Type = "Thức ăn" },
        new() { Word = "すいか", Romaji = "suika", Meaning = "dưa hấu", Type = "Thức ăn" },
        new() { Word = "もも", Romaji = "momo", Meaning = "đào", Type = "Thức ăn" },
        new() { Word = "さとう", Romaji = "satou", Meaning = "đường", Type = "Thức ăn" },
        new() { Word = "しお", Romaji = "shio", Meaning = "muối", Type = "Thức ăn" },
        new() { Word = "しょうゆ", Romaji = "shouyu", Meaning = "xì dầu", Type = "Thức ăn" },
        new() { Word = "みそ", Romaji = "miso", Meaning = "miso", Type = "Thức ăn" },
        new() { Word = "サラダ", Romaji = "sarada", Meaning = "salad", Type = "Thức ăn" },
        new() { Word = "スープ", Romaji = "suupu", Meaning = "súp", Type = "Thức ăn" },
        new() { Word = "カレー", Romaji = "karee", Meaning = "cà ri", Type = "Thức ăn" },
        new() { Word = "ハンバーガー", Romaji = "hanbaagaa", Meaning = "hamburger", Type = "Thức ăn" },
        new() { Word = "ケーキ", Romaji = "keeki", Meaning = "bánh ngọt", Type = "Thức ăn" },
        new() { Word = "アイスクリーム", Romaji = "aisukuriimu", Meaning = "kem", Type = "Thức ăn" },
        new() { Word = "チョコレート", Romaji = "chokoreeto", Meaning = "sô cô la", Type = "Thức ăn" },
        new() { Word = "おかし", Romaji = "okashi", Meaning = "bánh kẹo", Type = "Thức ăn" },
        new() { Word = "おにぎり", Romaji = "onigiri", Meaning = "cơm nắm", Type = "Thức ăn" },
        new() { Word = "すし", Romaji = "sushi", Meaning = "sushi", Type = "Thức ăn" },
        new() { Word = "ラーメン", Romaji = "raamen", Meaning = "mì ramen", Type = "Thức ăn" },
        new() { Word = "うどん", Romaji = "udon", Meaning = "mì udon", Type = "Thức ăn" },
        new() { Word = "そば", Romaji = "soba", Meaning = "mì soba", Type = "Thức ăn" },
        new() { Word = "とうふ", Romaji = "toufu", Meaning = "đậu phụ", Type = "Thức ăn" },
        new() { Word = "やきとり", Romaji = "yakitori", Meaning = "thịt gà nướng", Type = "Thức ăn" },
        new() { Word = "てんぷら", Romaji = "tempura", Meaning = "tempura", Type = "Thức ăn" },
        new() { Word = "おべんとう", Romaji = "obentou", Meaning = "cơm hộp", Type = "Thức ăn" },
        new() { Word = "のみもの", Romaji = "nomimono", Meaning = "đồ uống", Type = "Thức ăn" },
        new() { Word = "たべもの", Romaji = "tabemono", Meaning = "đồ ăn", Type = "Thức ăn" },

        // ===================== ĐỊA ĐIỂM =====================
        new() { Word = "がっこう", Romaji = "gakkou", Meaning = "trường học", Type = "Địa điểm" },
        new() { Word = "びょういん", Romaji = "byouin", Meaning = "bệnh viện", Type = "Địa điểm" },
        new() { Word = "こうばん", Romaji = "kouban", Meaning = "đồn cảnh sát", Type = "Địa điểm" },
        new() { Word = "ゆうびんきょく", Romaji = "yuubinkyoku", Meaning = "bưu điện", Type = "Địa điểm" },
        new() { Word = "ぎんこう", Romaji = "ginkou", Meaning = "ngân hàng", Type = "Địa điểm" },
        new() { Word = "としょかん", Romaji = "toshokan", Meaning = "thư viện", Type = "Địa điểm" },
        new() { Word = "こうえん", Romaji = "kouen", Meaning = "công viên", Type = "Địa điểm" },
        new() { Word = "えき", Romaji = "eki", Meaning = "ga tàu", Type = "Địa điểm" },
        new() { Word = "くうこう", Romaji = "kuukou", Meaning = "sân bay", Type = "Địa điểm" },
        new() { Word = "みなと", Romaji = "minato", Meaning = "cảng biển", Type = "Địa điểm" },
        new() { Word = "やま", Romaji = "yama", Meaning = "núi", Type = "Địa điểm" },
        new() { Word = "かわ", Romaji = "kawa", Meaning = "sông", Type = "Địa điểm" },
        new() { Word = "うみ", Romaji = "umi", Meaning = "biển", Type = "Địa điểm" },
        new() { Word = "みせ", Romaji = "mise", Meaning = "cửa hàng", Type = "Địa điểm" },
        new() { Word = "コンビニ", Romaji = "konbini", Meaning = "cửa hàng tiện lợi", Type = "Địa điểm" },
        new() { Word = "スーパー", Romaji = "suupaa", Meaning = "siêu thị", Type = "Địa điểm" },
        new() { Word = "デパート", Romaji = "depaato", Meaning = "trung tâm thương mại", Type = "Địa điểm" },
        new() { Word = "レストラン", Romaji = "resutoran", Meaning = "nhà hàng", Type = "Địa điểm" },
        new() { Word = "きっさてん", Romaji = "kissaten", Meaning = "quán cà phê", Type = "Địa điểm" },
        new() { Word = "ホテル", Romaji = "hoteru", Meaning = "khách sạn", Type = "Địa điểm" },
        new() { Word = "じむしょ", Romaji = "jimusho", Meaning = "văn phòng", Type = "Địa điểm" },
        new() { Word = "とし", Romaji = "toshi", Meaning = "thành phố", Type = "Địa điểm" },
        new() { Word = "まち", Romaji = "machi", Meaning = "thị trấn", Type = "Địa điểm" },
        new() { Word = "むら", Romaji = "mura", Meaning = "ngôi làng", Type = "Địa điểm" },
        new() { Word = "くに", Romaji = "kuni", Meaning = "đất nước", Type = "Địa điểm" },
        new() { Word = "にほん", Romaji = "nihon", Meaning = "Nhật Bản", Type = "Địa điểm" },
        new() { Word = "へや", Romaji = "heya", Meaning = "căn phòng", Type = "Địa điểm" },
        new() { Word = "にわ", Romaji = "niwa", Meaning = "sân vườn", Type = "Địa điểm" },
        new() { Word = "おてあらい", Romaji = "otearai", Meaning = "nhà vệ sinh", Type = "Địa điểm" },
        new() { Word = "おふろ", Romaji = "ofuro", Meaning = "phòng tắm", Type = "Địa điểm" },
        new() { Word = "だいどころ", Romaji = "daidokoro", Meaning = "phòng bếp", Type = "Địa điểm" },
        new() { Word = "アメリカ", Romaji = "amerika", Meaning = "Mỹ", Type = "Địa điểm" },
        new() { Word = "イギリス", Romaji = "igirisu", Meaning = "Anh", Type = "Địa điểm" },
        new() { Word = "フランス", Romaji = "furansu", Meaning = "Pháp", Type = "Địa điểm" },
        new() { Word = "ちゅうごく", Romaji = "chuugoku", Meaning = "Trung Quốc", Type = "Địa điểm" },
        new() { Word = "かんこく", Romaji = "kankoku", Meaning = "Hàn Quốc", Type = "Địa điểm" },
        new() { Word = "ベトナム", Romaji = "betonamu", Meaning = "Việt Nam", Type = "Địa điểm" },

        // ===================== TRƯỜNG HỌC =====================
        new() { Word = "せんせい", Romaji = "sensei", Meaning = "giáo viên", Type = "Trường học" },
        new() { Word = "がくせい", Romaji = "gakusei", Meaning = "học sinh", Type = "Trường học" },
        new() { Word = "だいがく", Romaji = "daigaku", Meaning = "đại học", Type = "Trường học" },
        new() { Word = "きょうしつ", Romaji = "kyoushitsu", Meaning = "lớp học", Type = "Trường học" },
        new() { Word = "じゅぎょう", Romaji = "jugyou", Meaning = "giờ học", Type = "Trường học" },
        new() { Word = "しゅくだい", Romaji = "shukudai", Meaning = "bài tập về nhà", Type = "Trường học" },
        new() { Word = "べんきょう", Romaji = "benkyou", Meaning = "việc học", Type = "Trường học" },
        new() { Word = "がくねん", Romaji = "gakunen", Meaning = "khối lớp", Type = "Trường học" },
        new() { Word = "しけん", Romaji = "shiken", Meaning = "kỳ thi", Type = "Trường học" },
        new() { Word = "テスト", Romaji = "tesuto", Meaning = "bài kiểm tra", Type = "Trường học" },
        new() { Word = "ノート", Romaji = "nooto", Meaning = "quyển vở", Type = "Trường học" },
        new() { Word = "えんぴつ", Romaji = "enpitsu", Meaning = "bút chì", Type = "Trường học" },
        new() { Word = "けしごむ", Romaji = "keshigomu", Meaning = "cục tẩy", Type = "Trường học" },
        new() { Word = "じしょ", Romaji = "jisho", Meaning = "từ điển", Type = "Trường học" },
        new() { Word = "きょうかしょ", Romaji = "kyoukasho", Meaning = "sách giáo khoa", Type = "Trường học" },
        new() { Word = "こくばん", Romaji = "kokuban", Meaning = "bảng đen", Type = "Trường học" },
        new() { Word = "ふでばこ", Romaji = "fudebako", Meaning = "hộp bút", Type = "Trường học" },
        new() { Word = "ともだち", Romaji = "tomodachi", Meaning = "bạn bè", Type = "Trường học" },
        new() { Word = "クラス", Romaji = "kurasu", Meaning = "lớp học", Type = "Trường học" },
        new() { Word = "せき", Romaji = "seki", Meaning = "chỗ ngồi", Type = "Trường học" },

        // ===================== CÔNG VIỆC =====================
        new() { Word = "しごと", Romaji = "shigoto", Meaning = "công việc", Type = "Công việc" },
        new() { Word = "かいしゃ", Romaji = "kaisha", Meaning = "công ty", Type = "Công việc" },
        new() { Word = "いしゃ", Romaji = "isha", Meaning = "bác sĩ", Type = "Công việc" },
        new() { Word = "かんごふ", Romaji = "kangofu", Meaning = "y tá", Type = "Công việc" },
        new() { Word = "けいさつかん", Romaji = "keisatsukan", Meaning = "cảnh sát", Type = "Công việc" },
        new() { Word = "うんてんしゅ", Romaji = "untenshu", Meaning = "tài xế", Type = "Công việc" },
        new() { Word = "てんいん", Romaji = "tenin", Meaning = "nhân viên bán hàng", Type = "Công việc" },
        new() { Word = "エンジニア", Romaji = "enjinia", Meaning = "kỹ sư", Type = "Công việc" },
        new() { Word = "べんごし", Romaji = "bengoshi", Meaning = "luật sư", Type = "Công việc" },
        new() { Word = "かいしゃいん", Romaji = "kaishain", Meaning = "nhân viên văn phòng", Type = "Công việc" },
        new() { Word = "きょうし", Romaji = "kyoushi", Meaning = "giáo viên", Type = "Công việc" },
        new() { Word = "のうみん", Romaji = "noumin", Meaning = "nông dân", Type = "Công việc" },
        new() { Word = "しゅふ", Romaji = "shufu", Meaning = "nội trợ", Type = "Công việc" },
        new() { Word = "アルバイト", Romaji = "arubaito", Meaning = "việc làm thêm", Type = "Công việc" },
        new() { Word = "きゅうりょう", Romaji = "kyuuryou", Meaning = "tiền lương", Type = "Công việc" },
        new() { Word = "たいへん", Romaji = "taihen", Meaning = "vất vả", Type = "Công việc" },

        // ===================== THỜI TIẾT =====================
        new() { Word = "てんき", Romaji = "tenki", Meaning = "thời tiết", Type = "Thời tiết" },
        new() { Word = "はれ", Romaji = "hare", Meaning = "trời nắng", Type = "Thời tiết" },
        new() { Word = "くもり", Romaji = "kumori", Meaning = "trời mây", Type = "Thời tiết" },
        new() { Word = "あめ", Romaji = "ame", Meaning = "mưa", Type = "Thời tiết" },
        new() { Word = "ゆき", Romaji = "yuki", Meaning = "tuyết", Type = "Thời tiết" },
        new() { Word = "かぜ", Romaji = "kaze", Meaning = "gió", Type = "Thời tiết" },
        new() { Word = "かみなり", Romaji = "kaminari", Meaning = "sấm chớp", Type = "Thời tiết" },
        new() { Word = "たいふう", Romaji = "taifuu", Meaning = "bão", Type = "Thời tiết" },
        new() { Word = "きり", Romaji = "kiri", Meaning = "sương mù", Type = "Thời tiết" },
        new() { Word = "そら", Romaji = "sora", Meaning = "bầu trời", Type = "Thời tiết" },
        new() { Word = "はる", Romaji = "haru", Meaning = "mùa xuân", Type = "Thời tiết" },
        new() { Word = "なつ", Romaji = "natsu", Meaning = "mùa hè", Type = "Thời tiết" },
        new() { Word = "あき", Romaji = "aki", Meaning = "mùa thu", Type = "Thời tiết" },
        new() { Word = "ふゆ", Romaji = "fuyu", Meaning = "mùa đông", Type = "Thời tiết" },
        new() { Word = "きせつ", Romaji = "kisetsu", Meaning = "mùa trong năm", Type = "Thời tiết" },
        new() { Word = "ひざし", Romaji = "hizashi", Meaning = "ánh nắng", Type = "Thời tiết" },

        // ===================== GIAO THÔNG =====================
        new() { Word = "くるま", Romaji = "kuruma", Meaning = "xe hơi", Type = "Giao thông" },
        new() { Word = "じてんしゃ", Romaji = "jitensha", Meaning = "xe đạp", Type = "Giao thông" },
        new() { Word = "でんしゃ", Romaji = "densha", Meaning = "tàu điện", Type = "Giao thông" },
        new() { Word = "ちかてつ", Romaji = "chikatetsu", Meaning = "tàu điện ngầm", Type = "Giao thông" },
        new() { Word = "ひこうき", Romaji = "hikouki", Meaning = "máy bay", Type = "Giao thông" },
        new() { Word = "ふね", Romaji = "fune", Meaning = "tàu thủy", Type = "Giao thông" },
        new() { Word = "バス", Romaji = "basu", Meaning = "xe buýt", Type = "Giao thông" },
        new() { Word = "タクシー", Romaji = "takushii", Meaning = "taxi", Type = "Giao thông" },
        new() { Word = "バイク", Romaji = "baiku", Meaning = "xe máy", Type = "Giao thông" },
        new() { Word = "トラック", Romaji = "torakku", Meaning = "xe tải", Type = "Giao thông" },
        new() { Word = "どうろ", Romaji = "douro", Meaning = "đường bộ", Type = "Giao thông" },
        new() { Word = "みち", Romaji = "michi", Meaning = "con đường", Type = "Giao thông" },
        new() { Word = "しんごう", Romaji = "shingou", Meaning = "đèn giao thông", Type = "Giao thông" },
        new() { Word = "こうさてん", Romaji = "kousaten", Meaning = "ngã tư", Type = "Giao thông" },
        new() { Word = "バスてい", Romaji = "basutei", Meaning = "trạm xe buýt", Type = "Giao thông" },
        new() { Word = "きっぷ", Romaji = "kippu", Meaning = "vé tàu/xe", Type = "Giao thông" },
        new() { Word = "うんてん", Romaji = "unten", Meaning = "lái xe", Type = "Giao thông" },

        // ===================== SỨC KHỎE =====================
        new() { Word = "からだ", Romaji = "karada", Meaning = "cơ thể", Type = "Sức khỏe" },
        new() { Word = "あたま", Romaji = "atama", Meaning = "cái đầu", Type = "Sức khỏe" },
        new() { Word = "かお", Romaji = "kao", Meaning = "khuôn mặt", Type = "Sức khỏe" },
        new() { Word = "め", Romaji = "me", Meaning = "mắt", Type = "Sức khỏe" },
        new() { Word = "はな", Romaji = "hana", Meaning = "mũi", Type = "Sức khỏe" },
        new() { Word = "みみ", Romaji = "mimi", Meaning = "tai", Type = "Sức khỏe" },
        new() { Word = "くち", Romaji = "kuchi", Meaning = "miệng", Type = "Sức khỏe" },
        new() { Word = "は", Romaji = "ha", Meaning = "răng", Type = "Sức khỏe" },
        new() { Word = "のど", Romaji = "nodo", Meaning = "cổ họng", Type = "Sức khỏe" },
        new() { Word = "て", Romaji = "te", Meaning = "bàn tay", Type = "Sức khỏe" },
        new() { Word = "あし", Romaji = "ashi", Meaning = "bàn chân", Type = "Sức khỏe" },
        new() { Word = "おなか", Romaji = "onaka", Meaning = "bụng", Type = "Sức khỏe" },
        new() { Word = "せなか", Romaji = "senaka", Meaning = "lưng", Type = "Sức khỏe" },
        new() { Word = "かた", Romaji = "kata", Meaning = "vai", Type = "Sức khỏe" },
        new() { Word = "ひざ", Romaji = "hiza", Meaning = "đầu gối", Type = "Sức khỏe" },
        new() { Word = "ゆび", Romaji = "yubi", Meaning = "ngón tay", Type = "Sức khỏe" },
        new() { Word = "つめ", Romaji = "tsume", Meaning = "móng tay", Type = "Sức khỏe" },
        new() { Word = "かみのけ", Romaji = "kaminoke", Meaning = "tóc", Type = "Sức khỏe" },
        new() { Word = "びょうき", Romaji = "byouki", Meaning = "bệnh tật", Type = "Sức khỏe" },
        new() { Word = "かぜ", Romaji = "kaze", Meaning = "cảm lạnh", Type = "Sức khỏe" },
        new() { Word = "くすり", Romaji = "kusuri", Meaning = "thuốc", Type = "Sức khỏe" },
        new() { Word = "ねつ", Romaji = "netsu", Meaning = "sốt", Type = "Sức khỏe" },
        new() { Word = "けが", Romaji = "kega", Meaning = "chấn thương", Type = "Sức khỏe" },
        new() { Word = "げんき", Romaji = "genki", Meaning = "sức khỏe", Type = "Sức khỏe" },
        new() { Word = "しんぱい", Romaji = "shinpai", Meaning = "lo lắng", Type = "Sức khỏe" },

        // ===================== MUA SẮM =====================
        new() { Word = "かいもの", Romaji = "kaimono", Meaning = "mua sắm", Type = "Mua sắm" },
        new() { Word = "ふく", Romaji = "fuku", Meaning = "quần áo", Type = "Mua sắm" },
        new() { Word = "シャツ", Romaji = "shatsu", Meaning = "áo sơ mi", Type = "Mua sắm" },
        new() { Word = "ズボン", Romaji = "zubon", Meaning = "quần dài", Type = "Mua sắm" },
        new() { Word = "スカート", Romaji = "sukaato", Meaning = "váy", Type = "Mua sắm" },
        new() { Word = "くつ", Romaji = "kutsu", Meaning = "giày", Type = "Mua sắm" },
        new() { Word = "くつした", Romaji = "kutsushita", Meaning = "tất/vớ", Type = "Mua sắm" },
        new() { Word = "ぼうし", Romaji = "boushi", Meaning = "cái mũ", Type = "Mua sắm" },
        new() { Word = "ネクタイ", Romaji = "nekutai", Meaning = "cà vạt", Type = "Mua sắm" },
        new() { Word = "ベルト", Romaji = "beruto", Meaning = "thắt lưng", Type = "Mua sắm" },
        new() { Word = "めがね", Romaji = "megane", Meaning = "kính mắt", Type = "Mua sắm" },
        new() { Word = "うでどけい", Romaji = "udedokei", Meaning = "đồng hồ đeo tay", Type = "Mua sắm" },
        new() { Word = "セーター", Romaji = "seetaa", Meaning = "áo len", Type = "Mua sắm" },
        new() { Word = "コート", Romaji = "kooto", Meaning = "áo khoác", Type = "Mua sắm" },
        new() { Word = "おかね", Romaji = "okane", Meaning = "tiền", Type = "Mua sắm" },
        new() { Word = "ねだん", Romaji = "nedan", Meaning = "giá cả", Type = "Mua sắm" },
        new() { Word = "げんきん", Romaji = "genkin", Meaning = "tiền mặt", Type = "Mua sắm" },
        new() { Word = "クレジットカード", Romaji = "kurejitto kaado", Meaning = "thẻ tín dụng", Type = "Mua sắm" },

        // ===================== SỞ THÍCH =====================
        new() { Word = "うた", Romaji = "uta", Meaning = "bài hát", Type = "Sở thích" },
        new() { Word = "おんがく", Romaji = "ongaku", Meaning = "âm nhạc", Type = "Sở thích" },
        new() { Word = "え", Romaji = "e", Meaning = "tranh vẽ", Type = "Sở thích" },
        new() { Word = "えいが", Romaji = "eiga", Meaning = "phim ảnh", Type = "Sở thích" },
        new() { Word = "しゃしん", Romaji = "shashin", Meaning = "ảnh chụp", Type = "Sở thích" },
        new() { Word = "スポーツ", Romaji = "supootsu", Meaning = "thể thao", Type = "Sở thích" },
        new() { Word = "サッカー", Romaji = "sakkaa", Meaning = "bóng đá", Type = "Sở thích" },
        new() { Word = "やきゅう", Romaji = "yakyuu", Meaning = "bóng chày", Type = "Sở thích" },
        new() { Word = "テニス", Romaji = "tenisu", Meaning = "quần vợt", Type = "Sở thích" },
        new() { Word = "バスケットボール", Romaji = "basukettobooru", Meaning = "bóng rổ", Type = "Sở thích" },
        new() { Word = "すいえい", Romaji = "suiei", Meaning = "bơi lội", Type = "Sở thích" },
        new() { Word = "りょこう", Romaji = "ryokou", Meaning = "du lịch", Type = "Sở thích" },
        new() { Word = "どくしょ", Romaji = "dokusho", Meaning = "đọc sách", Type = "Sở thích" },
        new() { Word = "りょうり", Romaji = "ryouri", Meaning = "nấu ăn", Type = "Sở thích" },
        new() { Word = "カラオケ", Romaji = "karaoke", Meaning = "hát karaoke", Type = "Sở thích" },
        new() { Word = "ダンス", Romaji = "dansu", Meaning = "khiêu vũ", Type = "Sở thích" },
        new() { Word = "ゲーム", Romaji = "geemu", Meaning = "trò chơi", Type = "Sở thích" },
        new() { Word = "はなみ", Romaji = "hanami", Meaning = "ngắm hoa", Type = "Sở thích" },
        new() { Word = "おまつり", Romaji = "omatsuri", Meaning = "lễ hội", Type = "Sở thích" },

        // ===================== ĐỘNG TỪ =====================
        new() { Word = "たべる", Romaji = "taberu", Meaning = "ăn", Type = "Động từ" },
        new() { Word = "のむ", Romaji = "nomu", Meaning = "uống", Type = "Động từ" },
        new() { Word = "かう", Romaji = "kau", Meaning = "mua", Type = "Động từ" },
        new() { Word = "うる", Romaji = "uru", Meaning = "bán", Type = "Động từ" },
        new() { Word = "みる", Romaji = "miru", Meaning = "xem", Type = "Động từ" },
        new() { Word = "きく", Romaji = "kiku", Meaning = "nghe", Type = "Động từ" },
        new() { Word = "はなす", Romaji = "hanasu", Meaning = "nói chuyện", Type = "Động từ" },
        new() { Word = "よむ", Romaji = "yomu", Meaning = "đọc", Type = "Động từ" },
        new() { Word = "かく", Romaji = "kaku", Meaning = "viết", Type = "Động từ" },
        new() { Word = "いく", Romaji = "iku", Meaning = "đi", Type = "Động từ" },
        new() { Word = "くる", Romaji = "kuru", Meaning = "đến", Type = "Động từ" },
        new() { Word = "する", Romaji = "suru", Meaning = "làm", Type = "Động từ" },
        new() { Word = "べんきょうする", Romaji = "benkyou suru", Meaning = "học bài", Type = "Động từ" },
        new() { Word = "しごとをする", Romaji = "shigoto o suru", Meaning = "làm việc", Type = "Động từ" },
        new() { Word = "やすむ", Romaji = "yasumu", Meaning = "nghỉ ngơi", Type = "Động từ" },
        new() { Word = "ねる", Romaji = "neru", Meaning = "ngủ", Type = "Động từ" },
        new() { Word = "おきる", Romaji = "okiru", Meaning = "thức dậy", Type = "Động từ" },
        new() { Word = "のる", Romaji = "noru", Meaning = "lên xe", Type = "Động từ" },
        new() { Word = "おりる", Romaji = "oriru", Meaning = "xuống xe", Type = "Động từ" },
        new() { Word = "あるく", Romaji = "aruku", Meaning = "đi bộ", Type = "Động từ" },
        new() { Word = "はしる", Romaji = "hashiru", Meaning = "chạy", Type = "Động từ" },
        new() { Word = "およぐ", Romaji = "oyogu", Meaning = "bơi", Type = "Động từ" },
        new() { Word = "あそぶ", Romaji = "asobu", Meaning = "chơi", Type = "Động từ" },
        new() { Word = "つくる", Romaji = "tsukuru", Meaning = "làm/chế tạo", Type = "Động từ" },
        new() { Word = "まつ", Romaji = "matsu", Meaning = "chờ đợi", Type = "Động từ" },
        new() { Word = "もつ", Romaji = "motsu", Meaning = "cầm/nắm", Type = "Động từ" },
        new() { Word = "とる", Romaji = "toru", Meaning = "lấy", Type = "Động từ" },
        new() { Word = "あける", Romaji = "akeru", Meaning = "mở", Type = "Động từ" },
        new() { Word = "しめる", Romaji = "shimeru", Meaning = "đóng", Type = "Động từ" },
        new() { Word = "でかける", Romaji = "dekakeru", Meaning = "ra ngoài", Type = "Động từ" },
        new() { Word = "かえる", Romaji = "kaeru", Meaning = "về nhà", Type = "Động từ" },
        new() { Word = "はいる", Romaji = "hairu", Meaning = "vào trong", Type = "Động từ" },
        new() { Word = "でる", Romaji = "deru", Meaning = "ra ngoài", Type = "Động từ" },
        new() { Word = "たつ", Romaji = "tatsu", Meaning = "đứng", Type = "Động từ" },
        new() { Word = "すわる", Romaji = "suwaru", Meaning = "ngồi", Type = "Động từ" },
        new() { Word = "あう", Romaji = "au", Meaning = "gặp gỡ", Type = "Động từ" },
        new() { Word = "もらう", Romaji = "morau", Meaning = "nhận", Type = "Động từ" },
        new() { Word = "あげる", Romaji = "ageru", Meaning = "tặng", Type = "Động từ" },
        new() { Word = "かす", Romaji = "kasu", Meaning = "cho mượn", Type = "Động từ" },
        new() { Word = "かりる", Romaji = "kariru", Meaning = "mượn", Type = "Động từ" },
        new() { Word = "つかう", Romaji = "tsukau", Meaning = "dùng", Type = "Động từ" },
        new() { Word = "おしえる", Romaji = "oshieru", Meaning = "dạy/chỉ", Type = "Động từ" },
        new() { Word = "ならう", Romaji = "narau", Meaning = "học tập", Type = "Động từ" },
        new() { Word = "わかる", Romaji = "wakaru", Meaning = "hiểu", Type = "Động từ" },
        new() { Word = "しる", Romaji = "shiru", Meaning = "biết", Type = "Động từ" },
        new() { Word = "おもう", Romaji = "omou", Meaning = "nghĩ", Type = "Động từ" },
        new() { Word = "いう", Romaji = "iu", Meaning = "nói", Type = "Động từ" },
        new() { Word = "みせる", Romaji = "miseru", Meaning = "cho xem", Type = "Động từ" },
        new() { Word = "きる", Romaji = "kiru", Meaning = "mặc (quần áo)", Type = "Động từ" },
        new() { Word = "ぬぐ", Romaji = "nugu", Meaning = "cởi (quần áo)", Type = "Động từ" },
        new() { Word = "あびる", Romaji = "abiru", Meaning = "tắm", Type = "Động từ" },
        new() { Word = "あらう", Romaji = "arau", Meaning = "rửa", Type = "Động từ" },
        new() { Word = "ふく", Romaji = "fuku", Meaning = "lau", Type = "Động từ" },
        new() { Word = "そうじする", Romaji = "souji suru", Meaning = "dọn dẹp", Type = "Động từ" },
        new() { Word = "せんたくする", Romaji = "sentaku suru", Meaning = "giặt giũ", Type = "Động từ" },
        new() { Word = "れんしゅうする", Romaji = "renshuu suru", Meaning = "luyện tập", Type = "Động từ" },
        new() { Word = "さんぽする", Romaji = "sanpo suru", Meaning = "đi dạo", Type = "Động từ" },

        // ===================== TÍNH TỪ (I-adjectives) =====================
        new() { Word = "おおきい", Romaji = "ookii", Meaning = "to/lớn", Type = "Tính từ" },
        new() { Word = "ちいさい", Romaji = "chiisai", Meaning = "nhỏ/bé", Type = "Tính từ" },
        new() { Word = "あたらしい", Romaji = "atarashii", Meaning = "mới", Type = "Tính từ" },
        new() { Word = "ふるい", Romaji = "furui", Meaning = "cũ", Type = "Tính từ" },
        new() { Word = "いい/よい", Romaji = "ii/yoi", Meaning = "tốt", Type = "Tính từ" },
        new() { Word = "わるい", Romaji = "warui", Meaning = "xấu/tệ", Type = "Tính từ" },
        new() { Word = "たかい", Romaji = "takai", Meaning = "cao/đắt", Type = "Tính từ" },
        new() { Word = "ひくい", Romaji = "hikui", Meaning = "thấp/rẻ", Type = "Tính từ" },
        new() { Word = "あつい", Romaji = "atsui", Meaning = "nóng", Type = "Tính từ" },
        new() { Word = "さむい", Romaji = "samui", Meaning = "lạnh", Type = "Tính từ" },
        new() { Word = "あたたかい", Romaji = "atatakai", Meaning = "ấm áp", Type = "Tính từ" },
        new() { Word = "すずしい", Romaji = "suzushii", Meaning = "mát mẻ", Type = "Tính từ" },
        new() { Word = "おもしろい", Romaji = "omoshiroi", Meaning = "thú vị", Type = "Tính từ" },
        new() { Word = "つまらない", Romaji = "tsumaranai", Meaning = "nhàm chán", Type = "Tính từ" },
        new() { Word = "たのしい", Romaji = "tanoshii", Meaning = "vui vẻ", Type = "Tính từ" },
        new() { Word = "かなしい", Romaji = "kanashii", Meaning = "buồn", Type = "Tính từ" },
        new() { Word = "うれしい", Romaji = "ureshii", Meaning = "vui mừng", Type = "Tính từ" },
        new() { Word = "こわい", Romaji = "kowai", Meaning = "đáng sợ", Type = "Tính từ" },
        new() { Word = "いたい", Romaji = "itai", Meaning = "đau", Type = "Tính từ" },
        new() { Word = "かわいい", Romaji = "kawaii", Meaning = "dễ thương", Type = "Tính từ" },
        new() { Word = "おいしい", Romaji = "oishii", Meaning = "ngon", Type = "Tính từ" },
        new() { Word = "まずい", Romaji = "mazui", Meaning = "dở/tệ", Type = "Tính từ" },
        new() { Word = "はやい", Romaji = "hayai", Meaning = "nhanh/sớm", Type = "Tính từ" },
        new() { Word = "おそい", Romaji = "osoi", Meaning = "chậm/muộn", Type = "Tính từ" },
        new() { Word = "とおい", Romaji = "tooi", Meaning = "xa", Type = "Tính từ" },
        new() { Word = "ちかい", Romaji = "chikai", Meaning = "gần", Type = "Tính từ" },
        new() { Word = "むずかしい", Romaji = "muzukashii", Meaning = "khó", Type = "Tính từ" },
        new() { Word = "やさしい", Romaji = "yasashii", Meaning = "dễ/dịu dàng", Type = "Tính từ" },
        new() { Word = "ほしい", Romaji = "hoshii", Meaning = "muốn", Type = "Tính từ" },
        new() { Word = "いそがしい", Romaji = "isogashii", Meaning = "bận rộn", Type = "Tính từ" },
        new() { Word = "ひろい", Romaji = "hiroi", Meaning = "rộng", Type = "Tính từ" },
        new() { Word = "せまい", Romaji = "semai", Meaning = "chật hẹp", Type = "Tính từ" },
        new() { Word = "あまい", Romaji = "amai", Meaning = "ngọt", Type = "Tính từ" },
        new() { Word = "からい", Romaji = "karai", Meaning = "cay", Type = "Tính từ" },
        new() { Word = "くらい", Romaji = "kurai", Meaning = "tối", Type = "Tính từ" },
        new() { Word = "あかるい", Romaji = "akarui", Meaning = "sáng sủa", Type = "Tính từ" },
        new() { Word = "ながい", Romaji = "nagai", Meaning = "dài", Type = "Tính từ" },
        new() { Word = "みじかい", Romaji = "mijikai", Meaning = "ngắn", Type = "Tính từ" },
        new() { Word = "おもい", Romaji = "omoi", Meaning = "nặng", Type = "Tính từ" },
        new() { Word = "かるい", Romaji = "karui", Meaning = "nhẹ", Type = "Tính từ" },
        new() { Word = "わかい", Romaji = "wakai", Meaning = "trẻ", Type = "Tính từ" },
        new() { Word = "すごい", Romaji = "sugoi", Meaning = "tuyệt vời", Type = "Tính từ" },

        // ===================== TÍNH TỪ (Na-adjectives) =====================
        new() { Word = "しずか", Romaji = "shizuka", Meaning = "yên tĩnh", Type = "Tính từ" },
        new() { Word = "にぎやか", Romaji = "nigiyaka", Meaning = "nhộn nhịp", Type = "Tính từ" },
        new() { Word = "げんき", Romaji = "genki", Meaning = "khỏe mạnh", Type = "Tính từ" },
        new() { Word = "しんせつ", Romaji = "shinsetsu", Meaning = "tốt bụng", Type = "Tính từ" },
        new() { Word = "ゆうめい", Romaji = "yuumei", Meaning = "nổi tiếng", Type = "Tính từ" },
        new() { Word = "たいせつ", Romaji = "taisetsu", Meaning = "quan trọng", Type = "Tính từ" },
        new() { Word = "べんり", Romaji = "benri", Meaning = "tiện lợi", Type = "Tính từ" },
        new() { Word = "ふべん", Romaji = "fuben", Meaning = "bất tiện", Type = "Tính từ" },
        new() { Word = "きれい", Romaji = "kirei", Meaning = "đẹp/sạch", Type = "Tính từ" },
        new() { Word = "じょうぶ", Romaji = "joubu", Meaning = "mạnh khỏe", Type = "Tính từ" },
        new() { Word = "すき", Romaji = "suki", Meaning = "thích", Type = "Tính từ" },
        new() { Word = "きらい", Romaji = "kirai", Meaning = "ghét", Type = "Tính từ" },
        new() { Word = "じょうず", Romaji = "jouzu", Meaning = "giỏi", Type = "Tính từ" },
        new() { Word = "へた", Romaji = "heta", Meaning = "dở/kém", Type = "Tính từ" },
        new() { Word = "だいすき", Romaji = "daisuki", Meaning = "rất thích", Type = "Tính từ" },
        new() { Word = "ひま", Romaji = "hima", Meaning = "rảnh rỗi", Type = "Tính từ" },
        new() { Word = "いろいろ", Romaji = "iroiro", Meaning = "nhiều loại", Type = "Tính từ" },
        new() { Word = "だいじ", Romaji = "daiji", Meaning = "quan trọng", Type = "Tính từ" },

        // ===================== TRẠNG TỪ =====================
        new() { Word = "とても", Romaji = "totemo", Meaning = "rất", Type = "Trạng từ" },
        new() { Word = "すこし", Romaji = "sukoshi", Meaning = "một chút", Type = "Trạng từ" },
        new() { Word = "たくさん", Romaji = "takusan", Meaning = "nhiều", Type = "Trạng từ" },
        new() { Word = "あまり", Romaji = "amari", Meaning = "không...lắm", Type = "Trạng từ" },
        new() { Word = "ぜんぜん", Romaji = "zenzen", Meaning = "hoàn toàn không", Type = "Trạng từ" },
        new() { Word = "もう", Romaji = "mou", Meaning = "đã...rồi", Type = "Trạng từ" },
        new() { Word = "まだ", Romaji = "mada", Meaning = "vẫn còn", Type = "Trạng từ" },
        new() { Word = "いつも", Romaji = "itsumo", Meaning = "luôn luôn", Type = "Trạng từ" },
        new() { Word = "たいてい", Romaji = "taitei", Meaning = "thường thường", Type = "Trạng từ" },
        new() { Word = "ときどき", Romaji = "tokidoki", Meaning = "thỉnh thoảng", Type = "Trạng từ" },
        new() { Word = "よく", Romaji = "yoku", Meaning = "thường xuyên", Type = "Trạng từ" },
        new() { Word = "だいたい", Romaji = "daitai", Meaning = "đại khái", Type = "Trạng từ" },
        new() { Word = "もちろん", Romaji = "mochiron", Meaning = "tất nhiên", Type = "Trạng từ" },
        new() { Word = "いっしょに", Romaji = "issho ni", Meaning = "cùng nhau", Type = "Trạng từ" },
        new() { Word = "すぐ", Romaji = "sugu", Meaning = "ngay lập tức", Type = "Trạng từ" },
        new() { Word = "ちゃんと", Romaji = "chanto", Meaning = "đúng đắn", Type = "Trạng từ" },
        new() { Word = "やっと", Romaji = "yatto", Meaning = "cuối cùng", Type = "Trạng từ" },
        new() { Word = "ぜひ", Romaji = "zehi", Meaning = "nhất định", Type = "Trạng từ" },
        new() { Word = "ちょっと", Romaji = "chotto", Meaning = "một chút", Type = "Trạng từ" },
        new() { Word = "また", Romaji = "mata", Meaning = "lại nữa", Type = "Trạng từ" },
        new() { Word = "はじめて", Romaji = "hajimete", Meaning = "lần đầu tiên", Type = "Trạng từ" },
        new() { Word = "ほとんど", Romaji = "hotondo", Meaning = "hầu như", Type = "Trạng từ" },

        // ===================== DANH TỪ (Question words & Others) =====================
        new() { Word = "なに/なん", Romaji = "nani/nan", Meaning = "cái gì", Type = "Danh từ" },
        new() { Word = "どこ", Romaji = "doko", Meaning = "ở đâu", Type = "Danh từ" },
        new() { Word = "いつ", Romaji = "itsu", Meaning = "khi nào", Type = "Danh từ" },
        new() { Word = "だれ", Romaji = "dare", Meaning = "ai", Type = "Danh từ" },
        new() { Word = "なぜ", Romaji = "naze", Meaning = "tại sao", Type = "Danh từ" },
        new() { Word = "どうして", Romaji = "doushite", Meaning = "tại sao", Type = "Danh từ" },
        new() { Word = "どの", Romaji = "dono", Meaning = "cái nào", Type = "Danh từ" },
        new() { Word = "どれ", Romaji = "dore", Meaning = "cái nào (3+ thứ)", Type = "Danh từ" },
        new() { Word = "どちら", Romaji = "dochira", Meaning = "bên nào", Type = "Danh từ" },
        new() { Word = "いくら", Romaji = "ikura", Meaning = "bao nhiêu tiền", Type = "Danh từ" },
        new() { Word = "どのくらい", Romaji = "donokurai", Meaning = "bao lâu", Type = "Danh từ" },
        new() { Word = "どう", Romaji = "dou", Meaning = "thế nào", Type = "Danh từ" },
        new() { Word = "なまえ", Romaji = "namae", Meaning = "tên", Type = "Danh từ" },
        new() { Word = "じゅうしょ", Romaji = "juusho", Meaning = "địa chỉ", Type = "Danh từ" },
        new() { Word = "でんわばんごう", Romaji = "denwa bangou", Meaning = "số điện thoại", Type = "Danh từ" },
        new() { Word = "こと", Romaji = "koto", Meaning = "sự việc", Type = "Danh từ" },
        new() { Word = "もの", Romaji = "mono", Meaning = "vật/đồ", Type = "Danh từ" },
        new() { Word = "ところ", Romaji = "tokoro", Meaning = "nơi chốn", Type = "Danh từ" },
        new() { Word = "みぎ", Romaji = "migi", Meaning = "bên phải", Type = "Danh từ" },
        new() { Word = "ひだり", Romaji = "hidari", Meaning = "bên trái", Type = "Danh từ" },
        new() { Word = "まえ", Romaji = "mae", Meaning = "phía trước", Type = "Danh từ" },
        new() { Word = "うしろ", Romaji = "ushiro", Meaning = "phía sau", Type = "Danh từ" },
        new() { Word = "うえ", Romaji = "ue", Meaning = "phía trên", Type = "Danh từ" },
        new() { Word = "した", Romaji = "shita", Meaning = "phía dưới", Type = "Danh từ" },
        new() { Word = "なか", Romaji = "naka", Meaning = "bên trong", Type = "Danh từ" },
        new() { Word = "そと", Romaji = "soto", Meaning = "bên ngoài", Type = "Danh từ" },
        new() { Word = "となり", Romaji = "tonari", Meaning = "kế bên", Type = "Danh từ" },
        new() { Word = "あいだ", Romaji = "aida", Meaning = "ở giữa", Type = "Danh từ" },
        new() { Word = "ちかく", Romaji = "chikaku", Meaning = "gần đây", Type = "Danh từ" },

        // ===================== DANH TỪ (Animals & Nature) =====================
        new() { Word = "いぬ", Romaji = "inu", Meaning = "con chó", Type = "Danh từ" },
        new() { Word = "ねこ", Romaji = "neko", Meaning = "con mèo", Type = "Danh từ" },
        new() { Word = "とり", Romaji = "tori", Meaning = "con chim", Type = "Danh từ" },
        new() { Word = "うま", Romaji = "uma", Meaning = "con ngựa", Type = "Danh từ" },
        new() { Word = "うし", Romaji = "ushi", Meaning = "con bò", Type = "Danh từ" },
        new() { Word = "ぶた", Romaji = "buta", Meaning = "con heo", Type = "Danh từ" },
        new() { Word = "ひつじ", Romaji = "hitsuji", Meaning = "con cừu", Type = "Danh từ" },
        new() { Word = "さる", Romaji = "saru", Meaning = "con khỉ", Type = "Danh từ" },
        new() { Word = "うさぎ", Romaji = "usagi", Meaning = "con thỏ", Type = "Danh từ" },
        new() { Word = "ぞう", Romaji = "zou", Meaning = "con voi", Type = "Danh từ" },
        new() { Word = "とら", Romaji = "tora", Meaning = "con hổ", Type = "Danh từ" },
        new() { Word = "くま", Romaji = "kuma", Meaning = "con gấu", Type = "Danh từ" },
        new() { Word = "へび", Romaji = "hebi", Meaning = "con rắn", Type = "Danh từ" },
        new() { Word = "かめ", Romaji = "kame", Meaning = "con rùa", Type = "Danh từ" },
        new() { Word = "さかな", Romaji = "sakana", Meaning = "con cá", Type = "Danh từ" },
        new() { Word = "むし", Romaji = "mushi", Meaning = "côn trùng", Type = "Danh từ" },
        new() { Word = "ちょう", Romaji = "chou", Meaning = "con bướm", Type = "Danh từ" },
        new() { Word = "はち", Romaji = "hachi", Meaning = "con ong", Type = "Danh từ" },
        new() { Word = "はな", Romaji = "hana", Meaning = "bông hoa", Type = "Danh từ" },
        new() { Word = "き", Romaji = "ki", Meaning = "cái cây", Type = "Danh từ" },
        new() { Word = "くさ", Romaji = "kusa", Meaning = "cỏ", Type = "Danh từ" },
        new() { Word = "いし", Romaji = "ishi", Meaning = "hòn đá", Type = "Danh từ" },
        new() { Word = "つち", Romaji = "tsuchi", Meaning = "đất", Type = "Danh từ" },
        new() { Word = "そら", Romaji = "sora", Meaning = "bầu trời", Type = "Danh từ" },
        new() { Word = "ほし", Romaji = "hoshi", Meaning = "ngôi sao", Type = "Danh từ" },
        new() { Word = "つき", Romaji = "tsuki", Meaning = "mặt trăng", Type = "Danh từ" },
        new() { Word = "たいよう", Romaji = "taiyou", Meaning = "mặt trời", Type = "Danh từ" },
        new() { Word = "ひ", Romaji = "hi", Meaning = "lửa", Type = "Danh từ" },
        new() { Word = "くも", Romaji = "kumo", Meaning = "mây", Type = "Danh từ" },

        // ===================== DANH TỪ (Greetings & Expressions) =====================
        new() { Word = "こんにちは", Romaji = "konnichiwa", Meaning = "xin chào", Type = "Danh từ" },
        new() { Word = "おはようございます", Romaji = "ohayou gozaimasu", Meaning = "chào buổi sáng", Type = "Danh từ" },
        new() { Word = "こんばんは", Romaji = "konbanwa", Meaning = "chào buổi tối", Type = "Danh từ" },
        new() { Word = "さようなら", Romaji = "sayounara", Meaning = "tạm biệt", Type = "Danh từ" },
        new() { Word = "ありがとうございます", Romaji = "arigatou gozaimasu", Meaning = "cảm ơn", Type = "Danh từ" },
        new() { Word = "すみません", Romaji = "sumimasen", Meaning = "xin lỗi", Type = "Danh từ" },
        new() { Word = "ごめんなさい", Romaji = "gomen nasai", Meaning = "xin lỗi", Type = "Danh từ" },
        new() { Word = "おやすみなさい", Romaji = "oyasumi nasai", Meaning = "chúc ngủ ngon", Type = "Danh từ" },
        new() { Word = "いただきます", Romaji = "itadakimasu", Meaning = "mời ăn", Type = "Danh từ" },
        new() { Word = "ごちそうさま", Romaji = "gochisousama", Meaning = "cảm ơn bữa ăn", Type = "Danh từ" },
        new() { Word = "はじめまして", Romaji = "hajimemashite", Meaning = "rất vui được gặp", Type = "Danh từ" },
        new() { Word = "よろしくおねがいします", Romaji = "yoroshiku onegaishimasu", Meaning = "mong được giúp đỡ", Type = "Danh từ" },
        new() { Word = "おねがいします", Romaji = "onegaishimasu", Meaning = "làm ơn", Type = "Danh từ" },
        new() { Word = "どういたしまして", Romaji = "dou itashimashite", Meaning = "không có gì", Type = "Danh từ" },
        new() { Word = "おめでとうございます", Romaji = "omedetou gozaimasu", Meaning = "chúc mừng", Type = "Danh từ" },
        new() { Word = "おたんじょうび", Romaji = "otanjoubi", Meaning = "sinh nhật", Type = "Danh từ" },
        new() { Word = "いいえ", Romaji = "iie", Meaning = "không", Type = "Danh từ" },
        new() { Word = "はい", Romaji = "hai", Meaning = "vâng", Type = "Danh từ" },
        new() { Word = "そうです", Romaji = "sou desu", Meaning = "đúng vậy", Type = "Danh từ" },
        new() { Word = "ちがいます", Romaji = "chigaimasu", Meaning = "không phải", Type = "Danh từ" },
        new() { Word = "わかりました", Romaji = "wakarimashita", Meaning = "đã hiểu", Type = "Danh từ" },
        new() { Word = "だいじょうぶ", Romaji = "daijoubu", Meaning = "ổn/không sao", Type = "Danh từ" },
        new() { Word = "いらっしゃいませ", Romaji = "irasshaimase", Meaning = "chào mừng", Type = "Danh từ" },
    };
}
