namespace JapLearn.Models;

public class Kana
{
    public string Character { get; set; } = "";
    public string Romaji { get; set; } = "";
    public string Type { get; set; } = "";

    public static List<Kana> All = new()
    {
        // Hiragana
        new() { Character = "あ", Romaji = "a", Type = "Hiragana" },
        new() { Character = "い", Romaji = "i", Type = "Hiragana" },
        new() { Character = "う", Romaji = "u", Type = "Hiragana" },
        new() { Character = "え", Romaji = "e", Type = "Hiragana" },
        new() { Character = "お", Romaji = "o", Type = "Hiragana" },
        new() { Character = "か", Romaji = "ka", Type = "Hiragana" },
        new() { Character = "き", Romaji = "ki", Type = "Hiragana" },
        new() { Character = "く", Romaji = "ku", Type = "Hiragana" },
        new() { Character = "け", Romaji = "ke", Type = "Hiragana" },
        new() { Character = "こ", Romaji = "ko", Type = "Hiragana" },
        new() { Character = "さ", Romaji = "sa", Type = "Hiragana" },
        new() { Character = "し", Romaji = "shi", Type = "Hiragana" },
        new() { Character = "す", Romaji = "su", Type = "Hiragana" },
        new() { Character = "せ", Romaji = "se", Type = "Hiragana" },
        new() { Character = "そ", Romaji = "so", Type = "Hiragana" },
        new() { Character = "た", Romaji = "ta", Type = "Hiragana" },
        new() { Character = "ち", Romaji = "chi", Type = "Hiragana" },
        new() { Character = "つ", Romaji = "tsu", Type = "Hiragana" },
        new() { Character = "て", Romaji = "te", Type = "Hiragana" },
        new() { Character = "と", Romaji = "to", Type = "Hiragana" },
        new() { Character = "な", Romaji = "na", Type = "Hiragana" },
        new() { Character = "に", Romaji = "ni", Type = "Hiragana" },
        new() { Character = "ぬ", Romaji = "nu", Type = "Hiragana" },
        new() { Character = "ね", Romaji = "ne", Type = "Hiragana" },
        new() { Character = "の", Romaji = "no", Type = "Hiragana" },
        new() { Character = "は", Romaji = "ha", Type = "Hiragana" },
        new() { Character = "ひ", Romaji = "hi", Type = "Hiragana" },
        new() { Character = "ふ", Romaji = "fu", Type = "Hiragana" },
        new() { Character = "へ", Romaji = "he", Type = "Hiragana" },
        new() { Character = "ほ", Romaji = "ho", Type = "Hiragana" },
        new() { Character = "ま", Romaji = "ma", Type = "Hiragana" },
        new() { Character = "み", Romaji = "mi", Type = "Hiragana" },
        new() { Character = "む", Romaji = "mu", Type = "Hiragana" },
        new() { Character = "め", Romaji = "me", Type = "Hiragana" },
        new() { Character = "も", Romaji = "mo", Type = "Hiragana" },
        new() { Character = "や", Romaji = "ya", Type = "Hiragana" },
        new() { Character = "ゆ", Romaji = "yu", Type = "Hiragana" },
        new() { Character = "よ", Romaji = "yo", Type = "Hiragana" },
        new() { Character = "ら", Romaji = "ra", Type = "Hiragana" },
        new() { Character = "り", Romaji = "ri", Type = "Hiragana" },
        new() { Character = "る", Romaji = "ru", Type = "Hiragana" },
        new() { Character = "れ", Romaji = "re", Type = "Hiragana" },
        new() { Character = "ろ", Romaji = "ro", Type = "Hiragana" },
        new() { Character = "わ", Romaji = "wa", Type = "Hiragana" },
        new() { Character = "を", Romaji = "wo", Type = "Hiragana" },
        new() { Character = "ん", Romaji = "n", Type = "Hiragana" },

        // Katakana
        new() { Character = "ア", Romaji = "a", Type = "Katakana" },
        new() { Character = "イ", Romaji = "i", Type = "Katakana" },
        new() { Character = "ウ", Romaji = "u", Type = "Katakana" },
        new() { Character = "エ", Romaji = "e", Type = "Katakana" },
        new() { Character = "オ", Romaji = "o", Type = "Katakana" },
        new() { Character = "カ", Romaji = "ka", Type = "Katakana" },
        new() { Character = "キ", Romaji = "ki", Type = "Katakana" },
        new() { Character = "ク", Romaji = "ku", Type = "Katakana" },
        new() { Character = "ケ", Romaji = "ke", Type = "Katakana" },
        new() { Character = "コ", Romaji = "ko", Type = "Katakana" },
        new() { Character = "サ", Romaji = "sa", Type = "Katakana" },
        new() { Character = "シ", Romaji = "shi", Type = "Katakana" },
        new() { Character = "ス", Romaji = "su", Type = "Katakana" },
        new() { Character = "セ", Romaji = "se", Type = "Katakana" },
        new() { Character = "ソ", Romaji = "so", Type = "Katakana" },
        new() { Character = "タ", Romaji = "ta", Type = "Katakana" },
        new() { Character = "チ", Romaji = "chi", Type = "Katakana" },
        new() { Character = "ツ", Romaji = "tsu", Type = "Katakana" },
        new() { Character = "テ", Romaji = "te", Type = "Katakana" },
        new() { Character = "ト", Romaji = "to", Type = "Katakana" },
        new() { Character = "ナ", Romaji = "na", Type = "Katakana" },
        new() { Character = "ニ", Romaji = "ni", Type = "Katakana" },
        new() { Character = "ヌ", Romaji = "nu", Type = "Katakana" },
        new() { Character = "ネ", Romaji = "ne", Type = "Katakana" },
        new() { Character = "ノ", Romaji = "no", Type = "Katakana" },
        new() { Character = "ハ", Romaji = "ha", Type = "Katakana" },
        new() { Character = "ヒ", Romaji = "hi", Type = "Katakana" },
        new() { Character = "フ", Romaji = "fu", Type = "Katakana" },
        new() { Character = "ヘ", Romaji = "he", Type = "Katakana" },
        new() { Character = "ホ", Romaji = "ho", Type = "Katakana" },
        new() { Character = "マ", Romaji = "ma", Type = "Katakana" },
        new() { Character = "ミ", Romaji = "mi", Type = "Katakana" },
        new() { Character = "ム", Romaji = "mu", Type = "Katakana" },
        new() { Character = "メ", Romaji = "me", Type = "Katakana" },
        new() { Character = "モ", Romaji = "mo", Type = "Katakana" },
        new() { Character = "ヤ", Romaji = "ya", Type = "Katakana" },
        new() { Character = "ユ", Romaji = "yu", Type = "Katakana" },
        new() { Character = "ヨ", Romaji = "yo", Type = "Katakana" },
        new() { Character = "ラ", Romaji = "ra", Type = "Katakana" },
        new() { Character = "リ", Romaji = "ri", Type = "Katakana" },
        new() { Character = "ル", Romaji = "ru", Type = "Katakana" },
        new() { Character = "レ", Romaji = "re", Type = "Katakana" },
        new() { Character = "ロ", Romaji = "ro", Type = "Katakana" },
        new() { Character = "ワ", Romaji = "wa", Type = "Katakana" },
        new() { Character = "ヲ", Romaji = "wo", Type = "Katakana" },
        new() { Character = "ン", Romaji = "n", Type = "Katakana" },
    };
}
